name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Generar snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: devpedro24
          outputs: dist/snake.svg

      - name: Subir a la rama output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
